//! End-to-end coverage for the owned native product command. The command's
//! source input is lowered and code-generated by LAMINARIA; this test only
//! supplies the Darwin runtime/link facts which the command deliberately
//! requires explicitly.

#![cfg(all(target_arch = "aarch64", target_os = "macos"))]

use std::path::{Path, PathBuf};
use std::process::Command;

fn laminaria_bin() -> &'static Path {
    Path::new(env!("CARGO_BIN_EXE_laminaria"))
}

fn temp_dir(name: &str) -> PathBuf {
    let root = std::env::temp_dir().join(format!(
        "laminaria-owned-native-build-cli-{name}-{}",
        std::process::id()
    ));
    let _ = std::fs::remove_dir_all(&root);
    std::fs::create_dir_all(&root).unwrap();
    root
}

fn macos_sdk_root() -> PathBuf {
    let output = Command::new("xcrun")
        .arg("--show-sdk-path")
        .output()
        .expect("xcrun must be available on the declared Darwin target");
    assert!(
        output.status.success(),
        "xcrun --show-sdk-path failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    PathBuf::from(String::from_utf8(output.stdout).unwrap().trim())
}

fn owned_native_command(source: &Path, output_dir: &Path) -> Command {
    owned_native_command_for_entry(source, output_dir, "main")
}

fn owned_native_command_for_entry(source: &Path, output_dir: &Path, entry: &str) -> Command {
    let mut command = Command::new(laminaria_bin());
    command
        .args(["owned-native-build", "--source"])
        .arg(source)
        .args(["--entry", entry])
        .args(["--output-dir"])
        .arg(output_dir)
        .args(["--linker", "/usr/bin/ld", "--sdk-root"])
        .arg(macos_sdk_root())
        .args(["--minimum-macos-version", "11.0", "--json"]);
    command
}

fn json_stdout(output: &std::process::Output) -> serde_json::Value {
    serde_json::from_slice(&output.stdout).unwrap_or_else(|error| {
        panic!(
            "expected JSON stdout ({error}); stdout: {}; stderr: {}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        )
    })
}

#[test]
fn owned_native_build_lowers_links_and_launches_supported_main() {
    let root = temp_dir("success");
    let source = root.join("main.rs");
    let output_dir = root.join("out");
    std::fs::write(&source, "fn main() -> i32 { 2i32.wrapping_add(5) }\n").unwrap();

    let output = owned_native_command(&source, &output_dir).output().unwrap();
    assert!(
        output.status.success(),
        "owned-native-build failed: stdout={} stderr={}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    let json = json_stdout(&output);
    assert_eq!(json["ok"], true);
    assert_eq!(json["result"]["entry"], "main");
    assert_eq!(json["result"]["toolchain"]["linker"], "/usr/bin/ld");
    assert_eq!(json["result"]["toolchain"]["minimum_macos_version"], "11.0");

    let object = PathBuf::from(json["result"]["object_path"].as_str().unwrap());
    let executable = PathBuf::from(json["result"]["executable_path"].as_str().unwrap());
    assert!(object.is_file(), "missing object: {}", object.display());
    assert!(
        executable.is_file(),
        "missing executable: {}",
        executable.display()
    );
    assert_eq!(Command::new(executable).status().unwrap().code(), Some(7));

    let _ = std::fs::remove_dir_all(root);
}

#[test]
fn owned_native_build_lowers_links_and_launches_source_conditional() {
    let root = temp_dir("conditional");
    let source = root.join("main.rs");
    let output_dir = root.join("out");
    std::fs::write(
        &source,
        r#"fn main() -> i32 {
            let zero = 3i32.wrapping_sub(3);
            if zero != 0 { 27 } else { 11 }
        }
        "#,
    )
    .unwrap();

    let output = owned_native_command(&source, &output_dir).output().unwrap();
    assert!(
        output.status.success(),
        "owned-native-build failed: stdout={} stderr={}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    let executable = PathBuf::from(
        json_stdout(&output)["result"]["executable_path"]
            .as_str()
            .unwrap(),
    );
    assert_eq!(Command::new(executable).status().unwrap().code(), Some(11));

    let _ = std::fs::remove_dir_all(root);
}

#[test]
fn owned_native_build_discovers_lowers_links_and_launches_transitive_calls() {
    let root = temp_dir("calls");
    let source = root.join("main.rs");
    let output_dir = root.join("out");
    std::fs::write(
        &source,
        r#"
        fn increment(x: i32) -> i32 { x.wrapping_add(1) }
        fn combine(x: i32) -> i32 { x.wrapping_add(increment(x)) }
        fn pack(left: i32, right: i32) -> i32 {
            left.wrapping_mul(10).wrapping_add(right)
        }
        fn main() -> i32 { pack(combine(3), increment(4)) }
        "#,
    )
    .unwrap();

    let output = owned_native_command(&source, &output_dir).output().unwrap();
    assert!(
        output.status.success(),
        "owned-native-build failed: stdout={} stderr={}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    let executable = PathBuf::from(
        json_stdout(&output)["result"]["executable_path"]
            .as_str()
            .unwrap(),
    );
    assert_eq!(Command::new(executable).status().unwrap().code(), Some(75));

    let _ = std::fs::remove_dir_all(root);
}

#[test]
fn owned_native_build_promotes_an_explicit_source_entry_to_darwin_main() {
    let root = temp_dir("explicit-entry");
    let source = root.join("main.rs");
    let output_dir = root.join("out");
    std::fs::write(
        &source,
        r#"
        fn increment(x: i32) -> i32 { x.wrapping_add(1) }
        fn laminaria_entry() -> i32 { increment(6) }
        fn main() { std::process::exit(laminaria_entry()); }
        "#,
    )
    .unwrap();

    let output = owned_native_command_for_entry(&source, &output_dir, "laminaria_entry")
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "owned-native-build failed: stdout={} stderr={}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    let json = json_stdout(&output);
    assert_eq!(json["result"]["entry"], "laminaria_entry");
    let executable = PathBuf::from(json["result"]["executable_path"].as_str().unwrap());
    assert_eq!(Command::new(executable).status().unwrap().code(), Some(7));

    let _ = std::fs::remove_dir_all(root);
}

#[test]
fn owned_native_build_reports_unsupported_source_before_linking() {
    let root = temp_dir("unsupported");
    let source = root.join("main.rs");
    let output_dir = root.join("out");
    std::fs::write(
        &source,
        "fn main() -> i32 { println!(\"not in the owned subset\"); 0i32 }\n",
    )
    .unwrap();

    let output = owned_native_command(&source, &output_dir).output().unwrap();
    assert!(!output.status.success());
    let json = json_stdout(&output);
    assert_eq!(json["ok"], false);
    assert_eq!(json["error_kind"], "source_diagnostic");
    assert!(json["detail"].as_str().unwrap().contains("macro"));
    assert!(
        !output_dir.exists(),
        "rejected source must not leave a link/output directory"
    );

    let _ = std::fs::remove_dir_all(root);
}
