//! `leaf-c` of the long-chain-wide-branches fixture (issue #28 D1-b2,
//! M7): `target = input % 256` looked up by a real binary search over
//! `PRIMES_UNDER_256` (fixed, ascending), returning the found index, or
//! `255` if `target` isn't prime (spec.md 2.2).

/// All 54 primes below 256, ascending -- independently regenerated by a
/// plain trial-division sieve (not transcribed from memory) and
/// confirmed to match this exact literal before adopting it.
const PRIMES_UNDER_256: [u8; 54] = [
    2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97,
    101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193,
    197, 199, 211, 223, 227, 229, 233, 239, 241, 251,
];

pub fn run(input: u64) -> u64 {
    let target = (input % 256) as u8;
    match PRIMES_UNDER_256.binary_search(&target) {
        Ok(index) => index as u64,
        Err(_) => 255,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn finds_a_present_prime() {
        // PRIMES_UNDER_256[24] == 97
        assert_eq!(run(97), 24);
    }

    #[test]
    fn returns_255_for_a_non_prime_target() {
        assert_eq!(run(100), 255);
    }
}
